# Generated by Django 4.2.2 on 2023-06-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0002_rename_contraseña_cliente_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='Cordoba', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveBigIntegerField(default=357211155),
            preserve_default=False,
        ),
    ]
