# Generated by Django 4.2.1 on 2023-05-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0006_alter_hotel_cuil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='contraseña',
            new_name='password',
        ),
    ]
