# Generated by Django 4.2.1 on 2023-06-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionReservas', '0002_imagen_habitacion_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='img/habitaciones'),
        ),
    ]
