# Generated by Django 4.2.2 on 2023-06-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionReservas', '0002_imagen_habitacion_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='img/habitaciones'),
        ),
    ]
